#!/bin/bash

state=$1
timer=$2
user=$(whoami)
user=${user^}

tcheck=$(date +%T | cut -c 1-3)

if [ $user = "www-data" ]; then
user="the Webserver"
fi

if [ -z $state ]; then
	exit 1

elif [ $state == "on" ] && [ -z $timer ]; then
	echo "Run by $user with state "$1" at $(date +%T)" >> /var/log/heat.log
	echo "" >> /var/log/heat.log
	echo "" > /var/www/onh.txt
	echo "on" > /var/www/heat.txt
	gpio -g write 14 0
	check=$(atq -q g | grep $tcheck | wc -l)
	if [ $check -gt 0 ]; then
		atrm $(atq -q g | cut -f1)
	fi
	exit 0

elif [ $state == "on" ] && [ $timer -gt 0 ]; then
	echo "Run by $user with state "$1" & timer "$2" at $(date +%T)" >> /var/log/heat.log
	echo "" >> /var/log/heat.log
	if [ $timer -lt "25" ] && [ $timer -gt "0" ]; then
		frame="hours"
	else
		frame="minutes"
	fi
	time=$(date -d "+$timer $frame" +"%T")
	/bin/bash /scripts/timed $timer $frame heat
	gpio -g write 14 0
	echo "on" > /var/www/heat.txt
	echo "The Heating is on until: $time" > /var/www/onh.txt
        check=$(atq -q g | grep $tcheck | wc -l)
        if [ $check -gt 0 ]; then
                atrm $(atq -q g | cut -f1)
        fi
	exit 0

elif [ $state == "off" ]; then
	echo "Run by $user with state "$1" at $(date +%T)" >> /var/log/heat.log
	echo "" >> /var/log/heat.log
	echo "" > /var/www/onh.txt
	echo "off" > /var/www/heat.txt
	gpio -g write 14 1
	check=$(atq -q g | grep $tcheck | wc -l)
	if [ $check -gt 0 ]; then
		atrm $(atq -q g | grep $tcheck | cut -f1)
	fi
	exit 0

else
	exit 1

fi

